[package]
name = "server-web"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4.0.1"
futures-util = "0.3"
rand = "0.8"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
time = "0.3"




